language: cpp
dist: trusty
matrix:
  include:
  - os: linux
    env: PYTHON=3.5
  - os: linux
    env: PYTHON=3.6
addons:
  apt:
    packages:
      - coinor-libclp-dev
      - python3-pip
install:
  - pip3 install --user -U pip setuptools virtualenv wheel
  - virtualenv -p python$PYTHON venv
  - source venv/bin/activate
script:
  - python setup.py install
  - python setup.py test
