language: python
python:
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
      - build-essential
      - coinor-libclp-dev
install:
  - pip install -U pip setuptools wheel pybind11
script:
  - python setup.py install
  - python setup.py test
